import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>My Verse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>My Verse program</h1>
    </div>
  );
}
