import Header from '../components/Header';

export default function Home() {
  return (
    <div>
      <>
        <title>My Verse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </>

      {/* header */}
      <Header />
      {/* body */}
      <div>this is the main page</div>
      {/* footer */}
    </div>
  );
}
