import Header from '../components/Header';
import Image from 'next/image';
import { MagnifyingGlassIcon, MicrophoneIcon } from '@heroicons/react/20/solid';
import Footer from '../components/Footer';
import { useRouter } from 'next/router';
import { useRef } from 'react';

export default function Home() {
  const router = useRouter();
  const searchInputRef = useRef(null);
  function search(event) {
    event.preventDefault();
    const term = searchInputRef.current.value;
    if (!term.trim()) return;
    router.push(`/search?term=${term.trim()}&searchType=`);
  }
  async function randomSearch(event) {
    event.preventDefault();
    const randomTerm = await fetch(
      'https://random-word-api.herokuapp.com/word?number=1'
    ).then((response) => response.json());
    if (!randomTerm) return;
    router.push(`/search?term=${randomTerm}&searchType=`);
  }
  return (
    <div>
      <>
        <title>My Verse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </>

      {/* header */}
      <Header />
      {/* body */}

      <form className="flex flex-col items-center mt-40">
        <div className="page_title">
          <h1
            onClick={() => router.push('/')}
            className=" text-2xl sm:text-5xl text-blue-800 font-bold mb-6"
          >
            The Word Of God
          </h1>
        </div>
        <Image
          width="250"
          objectFit="cover"
          height="100"
          src="/../public/images/Helmet-of-Salvation.jpg"
          alt="helmet of salvation"
          className="rounded-full 
          "
        />
        <p>Enter Your Verse Below</p>

        <div className="flex w-full mt-5 mx-auto max-w-[90%] bg-gray-50 border border-gray-300 hover:shadow-lg focus-within:shadow-lg px-5 py-3 rounded-full items-center sm:max-w-xl lg:max-w-2xl">
          <MagnifyingGlassIcon className="h-5 text-gray-500 mr-3" />

          <input
            ref={searchInputRef}
            type="text"
            className="flex-grow focus:outline-none"
          />

          {/* <MicrophoneIcon className="h-5" /> */}
        </div>
        <div
          className="flex flex-col sm:flex-row w-[50%]
         space-y-2 mt-8 sm:space-y-0 sm:space-x-4 justify-center"
        >
          <button onClick={search} className="btn">
            Verse Search
          </button>
          {/* <button onClick={randomSearch} className="btn">
            I&apos;m feeling lucky
          </button> */}
        </div>
      </form>

      {/* footer */}
      <Footer />
    </div>
  );
}
